#!/bin/bash
source `dirname $0`/common.sh
#set -x

if [ \! -d "$BUILD_DIR" ] 
then
    cmake -S . -B ${BUILD_DIR} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} 
    #-D "CMAKE_C_COMPILER:FILEPATH=$(which arm-none-eabi-gcc)"
fi

cmake --build ${BUILD_DIR}


